# Generated by Django 5.0.6 on 2024-10-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0031_rename_time_shows_end_time_shows_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
