# Generated by Django 5.0.6 on 2024-10-16 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0032_alter_shows_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='serie',
        ),
    ]
