# Generated by Django 5.0.6 on 2024-10-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0035_bookings_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='uuid',
        ),
    ]
