# Generated by Django 5.0.6 on 2024-10-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0038_shows_screen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='screen',
        ),
    ]
