# Generated by Django 5.0.6 on 2024-10-24 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0039_remove_bookings_uuid_remove_shows_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='shows',
            name='screen',
            field=models.CharField(default='Screen 1', max_length=300),
        ),
    ]
