# Generated by Django 5.0.6 on 2024-10-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0040_bookings_uuid_shows_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
