# Generated by Django 5.0.6 on 2024-10-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0042_remove_bookings_uuid_bookings_bookid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='book_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
