# Generated by Django 5.0.6 on 2024-10-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0043_payment_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
    ]
