# Generated by Django 5.0.6 on 2024-10-25 07:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0044_remove_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
    ]
