# Generated by Django 5.0.6 on 2024-10-29 04:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0046_bookings_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
