# Generated by Django 5.0.6 on 2024-10-29 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0047_bookings_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='is_canceled',
        ),
    ]
