# Generated by Django 5.0.6 on 2024-10-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0049_rename_amount_payment_price_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
