# Generated by Django 5.0.6 on 2024-11-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0054_comment_rating_delete_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
