# Generated by Django 5.0.6 on 2024-11-08 03:35

import django.db.models.deletion
import movie_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0056_alter_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='book_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='bookid',
            field=models.ForeignKey(default=movie_app.models.default_booking_id, on_delete=django.db.models.deletion.CASCADE, related_name='book_payment', to='movie_app.bookings'),
        ),
    ]
